web.http.default.port=8181
web.http.default.path=/
edc.participant.id=tap74-registry
edc.registry.url=http://localhost:8181/registry
edc.registry.oci.images=localhost:5000/xregistry-policies:current,localhost:5000/xregistry-dataspace-schemas:current
edc.registry.oci.poll.seconds=0
edc.registry.oci.insecure=true
